version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: 
          name: "Install MySQL Client 5.7"
          command: sudo apt update -y && sudo apt install -y default-mysql-client
      - run: 
          name: "Install bundler"
          command: gem install bundler --no-user-install
      - run:
          name: "Install Foreman"
          command: gem install foreman --no-user-install
      - run:
          name: "Install dependencies"
          command: bundle install  
      - run:
          name: "Running db create"
          command: cd db && bundle exec rake db:create
      - run:
          name: "Running db migration"
          command: cd db && bundle exec rake db:migrate  
      - run:
          name: "Running db seed"
          command: cd db && bundle exec rake db:seed               
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             