version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/mysql:5.7.27
    steps:
      - checkout
      - run:
          name: "Test connection MySQL"
          command: mysql -h ec2-54-215-104-48.us-west-1.compute.amazonaws.com -P 3307 -u $MYSQL_USER -p $MYSQL_PWD 
      - run: 
          name: "Install bundler"
          command: gem install bundler --no-user-install
      - run:
          name: "Install Foreman"
          command: gem install foreman --no-user-install
      - run:
          name: "Install dependencies"
          command: bundle install  
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             