version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: 
          name: "Build Image"
          command: docker build --tag backend:1.0 .
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             