version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/mysql:5.7-ram
    steps:
      - checkout
      - run: 
          name: "Upgrade OS"
          command: sudo apt-get update
      - run:
          name: "Install MySQL Client 5.7"
          command: sudo apt-get install mysql-client    
      - run: 
          name: "Install bundler"
          command: gem install bundler --no-user-install
      - run:
          name: "Install Foreman"
          command: gem install foreman --no-user-install
      - run:
          name: "Install dependencies"
          command: bundle install
      - run:
          name: "Running migration"
          command: cd db && bundle exec rake db:create        
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             