version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: 
          name: "Install bundler"
          command: gem install bundler
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             