version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: 
          name: "Upgrade OS"
          command: sudo yum update
      - run: 
          name: "Install bundler"
          command: gem install bundler --no-user-install
      - run:
          name: "Install Foreman"
          command: gem install foreman --no-user-install
      - run:
          name: "Install dependencies"
          command: bundle install
      - run:
          name: "Running migration"
          command: cd db && bundle exec rake db:create        
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
             