version: 2
jobs:
  build:
    working_directory: ~/limoneno
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: 
          name: "Install MySQL Client 5.7"
          command: sudo apt update -y && sudo apt install -y default-mysql-client
      - run: 
          name: "Install bundler"
          command: gem install bundler --no-user-install
      - run:
          name: "Install Foreman"
          command: gem install foreman --no-user-install
      - run:
          name: "Install dependencies"
          command: bundle install  
      - run:
          name: "Running db create"
          command: cd db && bundle exec rake db:create
      - run:
          name: "Running db migration"
          command: cd db && bundle exec rake db:migrate  
      - run:
          name: "Running db seed"
          command: cd db && bundle exec rake db:seed
  push:
      working_directory: ~/limoneno
      docker:
        - image: docker:18.06.1-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install dependencies
            command: |
              apk add py-pip
              pip install awscli
        - run:
            name: Login Amazon Elastic Container Registry 
            command: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 139689174177.dkr.ecr.us-west-1.amazonaws.com        
        - run: 
            name: "Build Image"
            command: docker build --tag limonenoback:latest .
        - run:
            name: Tag images Docker
            command: docker tag limonenoback:latest 139689174177.dkr.ecr.us-west-1.amazonaws.com/limoneno:latest
        - run:
            name: Push images Docker to Registry 
            command: docker push 139689174177.dkr.ecr.us-west-1.amazonaws.com/limoneno:latest            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push:
          requires:
            - build         